#!/bin/sh

# Copyright (c) 2011-2014 Ulrich Spoerlein <uqs@FreeBSD.org>
# Copyright (c) 2014-2015 Li-Wen Hsu <lwhsu@FreeBSD.org>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

DRY=

WORKDIR=`pwd -P`

SCAN_BUILD=/usr/local/bin/scan-build-devel

SRCDIR=${WORKDIR}/src
export OBJ=${WORKDIR}/obj
export MAKEOBJDIRPREFIX=${OBJ}
DEST=${WORKDIR}/clangScanBuildReports
SRCCONF=${WORKDIR}/freebsd-ci/scan-build/src.conf
MYFLAGS="__MAKE_CONF=/dev/null -m $SRCDIR/share/mk SRCCONF=${SRCCONF} -DMODULES_WITH_WORLD"
DATE=`date "+%Y-%m-%d"`
ARCH=`uname -p`
JFLAG=-j4

do_scan()
{
    local dir noclean output
    dir=$1; shift
    noclean=$1; shift
    output=$1; shift
    if [ -z "$DRY" ]; then
	mkdir -p $output || exit 1
	if [ -z "$noclean" ]; then
	    make ${JFLAG} $MYFLAGS clean
	    make ${JFLAG} $MYFLAGS obj
	fi
	echo "-=-> scanning $dir at `date "+%Y-%m-%d %H:%M:%S"`"
	/usr/bin/time -l \
	env CCC_ANALYZER_CHECKER_DEADCODE=0 \
	${SCAN_BUILD} \
	    --use-cc ${OBJ}${SRCDIR}/tmp/usr/bin/cc \
	    --use-c++ ${OBJ}${SRCDIR}/tmp/usr/bin/c++ \
	    -k -o $output make ${JFLAG} $MYFLAGS \
	    CROSS_COMPILER_PREFIX=${OBJ}${SRCDIR}/tmp/usr/bin/ "$@"
	rmdir $output 2>/dev/null
    else
	echo "$dir -> $output"
    fi
}

recurse_dirs()
{
    local prefix noclean dir subdirs srcpath limit depth
    limit=2
    prefix=$1; shift
    noclean=$1; shift
    set -- $*
    for dir in $*; do
	srcpath=$prefix/$dir
	srcpath=${srcpath#/}
	# only recurse, if 'make -n' returns exactly one line machting
	# /^for entry in/, as then there's nothing to do here, but there are subdirs
	(
	cd $dir
	depth=`echo "/$srcpath" |tr -Cd /`
	# pattern was found, and number of lines==1
	#echo $depth "${#depth}" "$limit"
	if [ "${#depth}" -le "$limit" ] && \
	    # grab MK_foo settings from head, not /usr/share/mk
	    make $MYFLAGS -n | awk '/for entry in/{found=1} END{if(found) exit NR-1; else exit 1}'; then
	    subdirs=`make $MYFLAGS -V SUBDIR`
	    recurse_dirs "$srcpath" "$noclean" `echo $subdirs`
	else
	    do_scan "$srcpath" "$noclean" $DEST/${SRCDIR##*/}/$(echo $srcpath|tr / .)
	fi
	)
    done
}

echo "-=-> scan-world started at `date "+%Y-%m-%d %H:%M:%S"`"

cd $SRCDIR || exit 1
rm -fr ${DEST}

if [ -z "$DRY" ]; then
    echo "-=-> Populating .OBJDIR"
    rm -rf "$OBJ"

    echo "-=-> Preparing build"
    make $MYFLAGS _worldtmp _legacy _bootstrap-tools _cleanobj _obj _build-tools _cross-tools
    echo "-=-> Preparing build (includes)"
    make $MYFLAGS _includes
    echo "-=-> Preparing build (libraries)"
    make $MYFLAGS _libraries
    echo "-=-> Preparing build (depend)"
    make $MYFLAGS CROSS_COMPILER_PREFIX=${OBJ}${SRCDIR}/tmp/usr/bin/ _depend
    if [ $? != 0 ]; then
	echo "Error during bootstrap" >&2
	exit 1
    fi
fi

# Need to have includes, as we hardcode clang for it, so no cleaning
echo "-=-> Building everything"
do_scan "$SRCDIR" "noclean" $DEST/${SRCDIR##*/}/WORLD -DNO_CLEAN -DNO_MODULES everything

echo "-=-> Building everything (again, individually)"
recurse_dirs "" "" lib libexec bin games cddl gnu kerberos5 sbin secure sys usr.bin usr.sbin
(
  for srcpath in cddl/usr.sbin/plockstat usr.bin/setchannel; do
      cd $SRCDIR/$srcpath
      do_scan "$srcpath" "" $DEST/${SRCDIR##*/}/$(echo $srcpath|tr / .)
  done
)

echo "-=-> Building GENERIC kernel"
do_scan "$SRCDIR" "noclean" $DEST/${SRCDIR##*/}/SYS.GENERIC -DNO_MODULES -DNO_CLEAN KERNCONF=GENERIC buildkernel

echo "-=-> Building LINT kernel"
make -C sys/$ARCH/conf LINT
do_scan "$SRCDIR" "noclean" $DEST/${SRCDIR##*/}/SYS.LINT -DNO_MODULES -DNO_CLEAN KERNCONF=LINT buildkernel

echo "-=-> scan-world finished at `date "+%Y-%m-%d %H:%M:%S"`"

if [ -z "$DRY" ]; then
    cd $DEST/${SRCDIR##*/} || exit 1

    echo "-=-> Renaming output dirs"
    find . -type d -name "${DATE}-*-[1-9]" -prune -exec sh -c 'd={}; mv "$d" "${d%-??????-*-[1-9]*}-'$ARCH'"' \;
fi
